// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KeketteTravel.Presentation.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Master {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Master() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KeketteTravel.Presentation.Localization.Master", typeof(Master).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        internal static string activitydetails_address {
            get {
                return ResourceManager.GetString("activitydetails_address", resourceCulture);
            }
        }
        
        internal static string activitydetails_coordinates {
            get {
                return ResourceManager.GetString("activitydetails_coordinates", resourceCulture);
            }
        }
        
        internal static string activitydetails_phonenumber {
            get {
                return ResourceManager.GetString("activitydetails_phonenumber", resourceCulture);
            }
        }
        
        internal static string activitydetails_websiteurl {
            get {
                return ResourceManager.GetString("activitydetails_websiteurl", resourceCulture);
            }
        }
        
        internal static string addactivity_title {
            get {
                return ResourceManager.GetString("addactivity_title", resourceCulture);
            }
        }
        
        internal static string addactivity_title_edit {
            get {
                return ResourceManager.GetString("addactivity_title_edit", resourceCulture);
            }
        }
        
        internal static string addactivity_name_hint {
            get {
                return ResourceManager.GetString("addactivity_name_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_description_hint {
            get {
                return ResourceManager.GetString("addactivity_description_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_street_hint {
            get {
                return ResourceManager.GetString("addactivity_street_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_postalcode_hint {
            get {
                return ResourceManager.GetString("addactivity_postalcode_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_city_hint {
            get {
                return ResourceManager.GetString("addactivity_city_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_latitude_hint {
            get {
                return ResourceManager.GetString("addactivity_latitude_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_longitude_hint {
            get {
                return ResourceManager.GetString("addactivity_longitude_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_website_hint {
            get {
                return ResourceManager.GetString("addactivity_website_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_phonenumber_hint {
            get {
                return ResourceManager.GetString("addactivity_phonenumber_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_photourl_hint {
            get {
                return ResourceManager.GetString("addactivity_photourl_hint", resourceCulture);
            }
        }
        
        internal static string addactivity_add {
            get {
                return ResourceManager.GetString("addactivity_add", resourceCulture);
            }
        }
        
        internal static string addactivity_name_error {
            get {
                return ResourceManager.GetString("addactivity_name_error", resourceCulture);
            }
        }
        
        internal static string addactivity_coordinates_error {
            get {
                return ResourceManager.GetString("addactivity_coordinates_error", resourceCulture);
            }
        }
        
        internal static string addactivity_edit {
            get {
                return ResourceManager.GetString("addactivity_edit", resourceCulture);
            }
        }
        
        internal static string countrydetails_map {
            get {
                return ResourceManager.GetString("countrydetails_map", resourceCulture);
            }
        }
        
        internal static string countrydetails_list {
            get {
                return ResourceManager.GetString("countrydetails_list", resourceCulture);
            }
        }
    }
}
